= Migration to Mule 4
ifndef::env-site,env-github[]
include::_attributes[]
endif::[]

// Introductory content extracted from
// https://blogs.mulesoft.com/dev/news-dev/mule-4-release-studio7/
Mule 4 expedites development of integration apps with up to 50% fewer steps and
concepts to learn than Mule 3, including:

* a simplified language for connectivity
* clear access to data
* automatic tuning
* easier upgrade processes

For your existing Mule 3 applications to take advantage of these and other benefits, you can migrate your apps to Mule through one of these processes:

//TODO: PROVIDE LINK TO MMA LANDING PAGE ON GITHUB WHEN IT IS AVAILABLE
* A partially automated migration with the Mule Migration Assistant (MMA), which
is available as an open source project on https://github.com/mulesoft/mule-migration-assistant[GitHub]. 
//TODO: NEED TO BE CLEAR ABOUT MMA LIMITATIONS: POINT OUT TO THE LIST OF WHAT'S MIGRATED AND WHAT'S NOT.
* A fully manual migration in which you build a Mule 4 version of the Mule 3 application from scratch.

//TODO: GUIDANCE ON WHEN TO USE MMA VS DOING A FULLY MANUAL MIGRATION, NEED SOME GUIDANCE
// What are the considerations? 
// Do we recommend they consider using the tool if MMA migrates some part of their app? 
// Do we recommend that they try MMA on their app to see if it's worth using it? 
// Do we ever recommend NOT using MMA 
//  (for ex, are there cases where MMA can't migrate anything or MMA makes the migration more complex? 

//BENEFITS OF MMA
== MMA 

A benefit of using MMA is that it automates part of the migration of Mule 3 apps to Mule 4. Though the MMA does not migrate the app entirely, it provides significant help with these tasks:

* Migrating the project structure.
* Automatically creating descriptor files, such as pom.xml or mule-artifact.json.
* Automatically performing many adaptations of the app’s code.
* Providing guidance on how to manually migrate components and patterns that cannot be migrated automatically.

MMA helps with such tasks, but it is not to be expected to deliver a fully functional app. Some additional steps are required. Those steps include testing and can also include:

* Manual migration of unsupported components.
* Manual migration of complex MEL expressions to DataWeave that cannot be automatically converted by MMA.
* Manual migration of complex DataWeave transformations that cannot be automatically converted by MMA.
* Prior migration of the DataMapper with the DataWeave Migration tool, before running the MMA.

//MANUAL MIGRATION

== Manual Migration
//TODO
// A completely manual migration involves building a Mule 4 application from scratch. 

== Migration Resources

//TODO: MORE DETAIL ON RESOURCES FOR MANUAL MIGRATION VS. MMA
Both migration scenarios require the same xref:migration-prep.adoc[preparation].

////
== See Also

* xref:migration-tutorial.adoc[Mule Migration Tool Tutorial]
* xref:migration-report.adoc[Mule Migration Report]
* xref:migration-tool-post-mig.adoc[Post-Migration Tasks]
////
