= Migration to Mule 4
ifndef::env-site,env-github[]
include::_attributes[]
endif::[]

// Introductory info extracted from
// https://blogs.mulesoft.com/dev/news-dev/mule-4-release-studio7/
Mule 4 expedites development of integration apps with up to 50% fewer steps and
concepts to learn than Mule 3, including:

* a simplified language for connectivity
* clear access to data
* automatic tuning
* easier upgrade processes
//TODO: OTHER BENEFITS ORDERED, WITH HIGHEST IMPACT LISTED BEFORE LOWER IMPACT BENEFITS

For existing Mule 3 apps to take advantage of these and other benefits, you can migrate your apps to Mule through one of these processes:

* A fully manual migration of connectors, modules, transports, expressions, and API gateways to their Mule 4 counterparts.
* A partially automated migration with the Mule Migration Assistant (MMA), which
is available as an open source project on https://github.com/mulesoft/mule-migration-assistant[GitHub].

== Understand the Migration Process

Before beginning the migration process, review documentation on how to
prepare for the migration and understand the basic steps of the migration.

* xref:migration-prep.doc[Preparing for a Migration to Mule 4]: Both migration scenarios require the same preparation.
* MMA migration process +
//TODO: GITHUB LOCATION 
* xref:migration-process.adoc[Manual Migration Process]

A benefit of using MMA is that it automates part of the migration of Mule 3 apps to Mule 4. Though the MMA does not migrate the app entirely, it provides significant help with these tasks:

* Migrating the project structure.
* Automatically creating descriptor files, such as pom.xml or mule-artifact.json.
* Automatically performing many adaptations of the app’s code.
* Providing guidance on how to manually migrate components and patterns that cannot be migrated automatically.

MMA helps with such tasks, but it is not to be expected to deliver a fully functional app. Some additional steps are required. Those steps include testing and can also include:

* Manual migration of unsupported components.
* Manual migration of complex MEL expressions to DataWeave that cannot be automatically converted by MMA.
* Manual migration of complex DataWeave transformations that cannot be automatically converted by MMA.
* Prior migration of the DataMapper with the DataWeave Migration tool, before running the MMA.

It is also important to note that the MMA does not support incremental migrations.

//TODO: GUIDANCE ON WHEN TO USE MMA VS DOING A FULLY MANUAL MIGRATION, NEED SOME GUIDANCE
// Any other considerations?
// Do we recommend they consider using the tool if MMA migrates some part of their app?
// Do we recommend that they try MMA on their app to see if it's worth using it?
// Do we ever recommend NOT using MMA
//  (for ex, are there cases where MMA can't migrate anything or MMA makes the migration more complex?

////
== See Also

* xref:migration-tutorial.adoc[Mule Migration Tool Tutorial]
* xref:migration-report.adoc[Mule Migration Report]
* xref:migration-tool-post-mig.adoc[Post-Migration Tasks]
////
